#!/usr/bin/env node
/**
 * build.mjs — tenant site generator (the RFC-002 "factory").
 * ---------------------------------------------------------------------------
 * Renders the shared template (public/index.html) plus a tenant's config and
 * assets (tenants/<slug>/) into a self-contained static bundle (dist/<slug>/):
 *
 *   • tenant.json is inlined as `window.__TENANT__` in <head> — no runtime
 *     fetch, no CORS, no flash (same mechanism as the edge Pages Function).
 *   • <title> and <meta description> are baked from config.meta (SEO / no-JS).
 *   • the Mode-B config-fetch <meta> is stripped (bundle is self-contained).
 *   • every asset in the tenant folder (logo, hero, …) is copied alongside
 *     index.html, so the JSON's relative paths (`logo.png`) just work.
 *
 * The output is a drop-anywhere static site — deploy it to any host (the
 * tenant's own Cloudflare Pages account, Netlify, etc.).
 *
 * Usage:
 *   node build.mjs <slug> [<slug> …]   # build specific tenant(s)
 *   node build.mjs                     # build all tenants under tenants/
 *   node build.mjs --all               # same as no args
 */

import { readFile, writeFile, readdir, mkdir, copyFile, rm, stat } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const TENANTS_DIR = path.join(ROOT, 'tenants');
const DIST_DIR = path.join(ROOT, 'dist');
const TEMPLATE = path.join(ROOT, 'public', 'index.html');
const CONFIG_FILE = 'tenant.json';

const banner = (slug) =>
  `<!--\n` +
  `  GENERATED by build.mjs — DO NOT EDIT THIS FILE.\n` +
  `  Source of truth: tenants/${slug}/${CONFIG_FILE} (+ assets in that folder)\n` +
  `  Rebuild:         node build.mjs ${slug}\n` +
  `-->`;

const escHtml = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const escAttr = (s) => String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');

function render(template, config, slug) {
  let html = template;

  // 1. Drop the Mode-B config-fetch <meta> (and its now-moot doc comment) —
  //    the bundle carries its own config.
  html = html.replace(/\n?[ \t]*<!--[\s\S]*?TENANT CONFIG SOURCE[\s\S]*?-->/i, '');
  html = html.replace(/\n?[ \t]*<meta name="tenant-config-base"[^>]*>/i, '');

  // 2. Bake <title> + description so the head is correct even before JS runs.
  if (config.meta?.title) {
    html = html.replace(/<title>[\s\S]*?<\/title>/i, `<title>${escHtml(config.meta.title)}</title>`);
  }
  if (config.meta?.description) {
    html = html.replace(/(<meta name="description" content=")[^"]*(")/i,
      `$1${escAttr(config.meta.description)}$2`);
  }

  // 3. Inline the config. Escape `<` so a value can't break out of <script>
  //    (identical to the edge Function's ConfigInjector).
  const json = JSON.stringify(config).replace(/</g, '\\u003c');
  html = html.replace(/<\/head>/i,
    `  ${banner(slug)}\n  <script>window.__TENANT__=${json};</script>\n</head>`);

  return html;
}

async function listTenants() {
  if (!existsSync(TENANTS_DIR)) return [];
  const entries = await readdir(TENANTS_DIR, { withFileTypes: true });
  return entries.filter((e) => e.isDirectory()).map((e) => e.name).sort();
}

async function buildTenant(slug, template) {
  const srcDir = path.join(TENANTS_DIR, slug);
  const cfgPath = path.join(srcDir, CONFIG_FILE);
  if (!existsSync(cfgPath)) throw new Error(`missing ${path.relative(ROOT, cfgPath)}`);

  let config;
  try {
    config = JSON.parse(await readFile(cfgPath, 'utf8'));
  } catch (e) {
    throw new Error(`invalid JSON in ${slug}/${CONFIG_FILE}: ${e.message}`);
  }

  const outDir = path.join(DIST_DIR, slug);
  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });
  await writeFile(path.join(outDir, 'index.html'), render(template, config, slug));

  // Copy assets: everything in the tenant folder except the config file.
  const entries = await readdir(srcDir);
  const assets = [];
  for (const name of entries) {
    if (name === CONFIG_FILE) continue;
    if ((await stat(path.join(srcDir, name))).isFile()) {
      await copyFile(path.join(srcDir, name), path.join(outDir, name));
      assets.push(name);
    }
  }

  // Light validation — surface problems without failing the build.
  const warnings = [];
  for (const ref of [config.brand?.logoUrl, config.hero?.image].filter(Boolean)) {
    if (!/^(https?:|data:)/i.test(ref) && !assets.includes(ref)) {
      warnings.push(`referenced asset not found in folder: "${ref}"`);
    }
  }
  if (!config.links?.androidUrl) warnings.push('links.androidUrl is empty (pending)');
  if (config.privacy && !config.privacy.effectiveDate) warnings.push('privacy.effectiveDate is empty (pending)');

  return { outDir: path.relative(ROOT, outDir), assets, warnings };
}

// Write a staging gallery (dist/index.html) linking every built tenant.
// Themed per tenant from its config (logo + primary color). This is the
// team-facing "factory + staging preview" index — deploy dist/ to a Pages
// project and browse /<slug>/.
async function writeGallery() {
  const entries = existsSync(DIST_DIR) ? await readdir(DIST_DIR, { withFileTypes: true }) : [];
  const built = [];
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    const slug = e.name;
    if (!existsSync(path.join(DIST_DIR, slug, 'index.html'))) continue;
    let cfg = {};
    try { cfg = JSON.parse(await readFile(path.join(TENANTS_DIR, slug, CONFIG_FILE), 'utf8')); } catch { /* keep defaults */ }
    const tok = cfg.tokens || {};
    built.push({
      slug,
      name: cfg.brand?.name || slug,
      logo: cfg.brand?.logoUrl || null,
      accent: tok['color-primary'] || tok['--color-primary'] || '#1a1a2e',
    });
  }
  built.sort((a, b) => a.slug.localeCompare(b.slug));

  const cards = built.map((t) => {
    // A data:/http logo is used as-is; a bare filename lives inside the bundle.
    const logoSrc = t.logo
      ? (/^(https?:|data:)/i.test(t.logo) ? t.logo : `./${encodeURIComponent(t.slug)}/${t.logo}`)
      : null;
    return `
      <a class="card" href="./${encodeURIComponent(t.slug)}/" style="--accent:${escAttr(t.accent)}">
        <span class="bar"></span>
        ${logoSrc
          ? `<img class="logo" src="${escAttr(logoSrc)}" alt="">`
          : `<span class="logo logo--none">${escHtml((t.name || t.slug).slice(0, 2).toUpperCase())}</span>`}
        <span class="name">${escHtml(t.name)}</span>
        <span class="slug">/${escHtml(t.slug)}/</span>
        <span class="open">Open preview →</span>
      </a>`;
  }).join('');

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Tenant Previews — Staging</title>
<!-- GENERATED by build.mjs — DO NOT EDIT. Rebuild: npm run build -->
<style>
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:'Segoe UI',system-ui,sans-serif;background:#f2f4f8;color:#1a1a2e;padding:48px 24px}
  .wrap{max-width:1000px;margin:0 auto}
  h1{font-size:1.6rem;display:flex;align-items:center;gap:12px}
  .tag{font-size:.6rem;font-weight:700;letter-spacing:.1em;text-transform:uppercase;background:#e2e8f0;color:#475569;padding:4px 9px;border-radius:999px}
  .sub{color:#64748b;font-size:.9rem;margin:8px 0 32px}
  .grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:20px}
  .card{position:relative;display:flex;flex-direction:column;align-items:flex-start;gap:8px;background:#fff;border-radius:12px;padding:26px 22px 20px;text-decoration:none;color:inherit;box-shadow:0 2px 12px rgba(0,0,0,.06);border:1px solid #e8edf3;overflow:hidden;transition:transform .15s,box-shadow .15s}
  .card:hover{transform:translateY(-3px);box-shadow:0 10px 26px rgba(0,0,0,.12)}
  .bar{position:absolute;top:0;left:0;right:0;height:5px;background:var(--accent)}
  .logo{width:54px;height:54px;object-fit:contain;border-radius:9px;background:#fff;border:1px solid #eef2f7;padding:4px}
  .logo--none{display:flex;align-items:center;justify-content:center;font-weight:800;color:#fff;background:var(--accent);font-size:1.1rem}
  .name{font-weight:700;font-size:1rem;line-height:1.3}
  .slug{font-size:.8rem;color:#94a3b8;font-family:ui-monospace,SFMono-Regular,monospace}
  .open{margin-top:6px;font-size:.85rem;font-weight:600;color:var(--accent)}
</style>
</head>
<body>
  <div class="wrap">
    <h1>Tenant Previews <span class="tag">staging</span></h1>
    <p class="sub">${built.length} tenant site${built.length === 1 ? '' : 's'} · generated by build.mjs · do not edit by hand</p>
    <div class="grid">${cards || '<p>No tenants built yet — run <code>npm run build</code>.</p>'}</div>
  </div>
</body>
</html>
`;
  await writeFile(path.join(DIST_DIR, 'index.html'), html);
  return built.length;
}

async function main() {
  const slugs = process.argv.slice(2).filter((a) => a !== '--all');
  const targets = slugs.length ? slugs : await listTenants();

  if (!targets.length) {
    console.error('No tenants found under tenants/. Nothing to build.');
    process.exit(1);
  }

  const template = await readFile(TEMPLATE, 'utf8');
  let failed = 0;

  for (const slug of targets) {
    try {
      const { outDir, assets, warnings } = await buildTenant(slug, template);
      console.log(`✓ ${slug} → ${outDir}  (${assets.length} asset${assets.length === 1 ? '' : 's'})`);
      warnings.forEach((w) => console.log(`  ⚠ ${w}`));
    } catch (e) {
      failed++;
      console.error(`✗ ${slug}: ${e.message}`);
    }
  }

  const listed = await writeGallery();
  console.log(`\n${targets.length - failed}/${targets.length} tenant(s) built.`);
  console.log(`Gallery: dist/index.html (${listed} tenant${listed === 1 ? '' : 's'} listed)`);
  process.exit(failed ? 1 : 0);
}

main();
